start: line*

line: call _NEWLINE?

call: FUNCTION_NAME "(" parameters ")"

parameters: parameter ("," " "* parameter)* 

parameter: PARAMETER_NAME ":" " "* parameter_value

parameter_value: ESCAPED_STRING | int_with_unit | INT

int_with_unit: INT _UNIT

FUNCTION_NAME: CNAME
PARAMETER_NAME: CNAME
_UNIT: "%" | "s" | "ms" | "deg" | "rad"
_NEWLINE: "\n"

%import common.CNAME
%import common.ESCAPED_STRING
%import common.INT
