start: line*

line: call _NEWLINE?

call: FUNCTION_NAME "(" parameters ")"

parameters: parameter ("," " "* parameter)* 

parameter: PARAMETER_NAME ":" " "* parameter_value

parameter_value: number_with_unit

number_with_unit: SIGNED_NUMBER UNIT

FUNCTION_NAME: CNAME
PARAMETER_NAME: CNAME
UNIT: WORD | "%"
_NEWLINE: "\n"

%import common.CNAME
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WORD
